apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: i9ib57hhm-nodejs 
  janus-idp.io/tekton: i9ib57hhm-nodejs
  backstage.io/kubernetes-id: i9ib57hhm-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: i9ib57hhm-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml