apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: i9ib57hhm-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: i9ib57hhm-nodejs 
  name: i9ib57hhm-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: i9ib57hhm-nodejs 
